### ISSUE TITLE
LED component

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pychargedup#29]
# Hardware

- Addressable RGB LED strip

# Methods

A lot of this can be copied straight from last year's code, but we should go further this year to help orchestrate our state machines. This will mean that we should make methods to indicate specific states of the robot rather than just setting raw patterns. Something like ```requesting_cone``` would be good and then under the hood, we define the mode of flash and colour under the hood for each method.

# Sensing

- None

**Comment by Pokesi** [comment]
PR #22 includes these functions:
```py
   def set_piece(self, piece: Piece):

    def set_state(self, state: RobotState):
       
    def set_intake_side(self, side: PickupFromSide):
``` 

which you can use in combination to request a piece (`set_piece`), the side of the loading station you want to pick it up from (`set_intake_side`) and - finally - `set_state` to say if you are:
 - Looking for a piece
 - Holding a piece
 - Doing anything else
