### ISSUE TITLE
Intake State Machine

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pychargedup#30]
# Components

- Intake

# States

- Intaking 
- Retracted

# Thoughts

This state machine is pretty straightforward. It will just orchestrate the transitions between the two states of the intake mechanism. The bit still open to discussion is how we should trigger transitions between these states. It could be timed, but I think it will be better if we have at least one sensor involved to automate the sequence. To do this we will need to run some tests and think about what will work best here ;)

**Comment by DensityInfinite** [comment]
I have this idea of, when the driver presses the button, the `intaking` state will be active until the intake succeeds (e.g. an object pass through a break-beam sensor); when the driver press and holds the button, the intake will keep intaking untili the driver lets go of the button.
Would that be suitable for this case?

**Comment by OliverW10** [comment]
We are going to have this logic in the intake controller now
