### ISSUE TITLE
Scoring State Machine

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pychargedup#31]
# Components

- Arm
- Gripper
- LEDs

# States

In my mind, this is an uber state machine because we need to control the gripper and the arm to pick and place game pieces and convey the robot's intention through a human-machine interface. 

- Game piece-specific states
  - Grabbing cone
  - Grabbing cube
  - Scoring cone
  - Scoring cube

- Common states
  - driving
  - aligning
  - deploying
  - recovering 

# Thoughts

We will also need to think carefully about how we can abort from this state machine and recover appropriately if required. If we do this, it will need to take control of driving the robot, and we want to ensure that we can give ownership back to the drivers properly without causing any long-lasting problems on the bot. We will also want to let them know when they have complete control. We definitely need to draw this one out and make a solid plan before attacking this in code. Again sensors are going to be essential to aid in these transitions so get thinking ;)

**Comment by Pokesi** [comment]
Am gonna begin writing this, we can work on the aborting code (error handling?). Though if it needs to control the arm component we need to decide on an interface for it as mentioned in #33

**Comment by OliverW10** [comment]
After discussion we have decided on these states:
- Pickup Cone
- Pickup Cube Ground
- Pickup Cube loading bay?
- Score cone
- Score cube
- recovery (must finish)
Each state will set the movement controllers goal and tell the arm and gripper component what to do at what times, assume the movement controller has a time_to_goal and at_goal methods.

The driver will hold a button to engage the state machine and it will work out what state to be in, have a goto_correct_state method that will do this. When the button is released put the state machine in recovery.
